# Generated by Django 3.1.2 on 2020-12-19 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnTrack', '0005_auto_20201218_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OnTrack.customer'),
        ),
    ]
