# Generated by Django 3.1.2 on 2021-01-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnTrack', '0007_habits'),
    ]

    operations = [
        migrations.AddField(
            model_name='goals',
            name='goalcompleteset',
            field=models.IntegerField(null=True),
        ),
    ]
